output:
- file: twin_pipe_log.csv
  topic: state/twin_pipe
- file: true_pipe_log.csv
  topic: state/true_pipe
- file: identified_params_log.json
  topic: identified_parameters/twin_pipe
simulation:
  end_time: 20000
  real_time_factor: 1.0
  start_time: 0.0
  time_step: 100
