# -*- coding: utf-8 -*-

import pandas as pd
from core_lib.core.interfaces import Agent

class LLMDataAnalystAgent(Agent):
    """
    Implements Role 4: Data Analyst & Diagnostic Expert.

    This agent is designed for post-simulation analysis. It takes simulation
    log data (e.g., a CSV file), prepares a summary, and uses a (simulated)
    LLM call to generate insights, identify anomalies, and suggest improvements.
    """
    def __init__(self, agent_id: str, message_bus=None):
        # This agent can operate standalone, so message_bus is optional.
        super().__init__(agent_id, message_bus)

    def run(self, current_time: float):
        # This is a post-processing agent, not used in a time-step simulation.
        pass

    def step(self, t: int, dt: int):
        # This is a post-processing agent, not used in a time-step simulation.
        pass

    def analyze_results(self, log_file_path: str, query: str) -> str:
        """
        Analyzes a simulation log file to answer a user's query.

        Args:
            log_file_path (str): The path to the CSV log file.
            query (str): The user's question, e.g., "Summarize the results." or
                         "Why did the water level of reservoir_1 exceed the limit?"

        Returns:
            str: A natural language report generated by the LLM.
        """
        print(f"[{self.id}] Analyzing log file: '{log_file_path}'")
        print(f"[{self.id}] User query: '{query}'")

        try:
            df = pd.read_csv(log_file_path)
            # For large files, we would sample or summarize the data before sending to LLM.
            data_summary = df.describe().to_string()
            data_head = df.head().to_string()
        except Exception as e:
            return f"Error reading or processing log file: {e}"

        print(f"[{self.id}] Data summary prepared. Calling LLM for analysis...")
        
        analysis_report = self._call_llm_for_analysis(data_summary, data_head, query)
        
        print(f"[{self.id}] Analysis complete.")
        return analysis_report

    def _call_llm_for_analysis(self, data_summary: str, data_head: str, query: str) -> str:
        """
        [SIMULATED] Simulates a call to an LLM for data analysis.

        A real implementation would pass the data summary and the query
        in a detailed prompt.
        """
        prompt = f"""
        Here is a summary of simulation data:
        --- SUMMARY ---
        {data_summary}

        --- DATA HEAD ---
        {data_head}
        ---
        User Query: "{query}"

        Please provide a concise analysis based on the data.
        """
        # print("DEBUG: LLM Prompt:\n", prompt) # For debugging

        # --- Hardcoded Responses for Demonstration ---
        query_lower = query.lower()
        if "summarize" in query_lower:
            return """
Analysis Report: Simulation Summary
------------------------------------
The simulation ran successfully. Key observations:
- Reservoir_1 water level fluctuated between 138.5m and 142.1m.
- Gate_1 opening percentage varied significantly, indicating active control.
- System appears stable, but there is a notable oscillation in channel flow.

Recommendation: Investigate PID controller tuning for Gate_1 to reduce flow oscillation.
            """
        elif "why" in query_lower and "exceed" in query_lower:
            return """
Root Cause Analysis Report: Water Level Anomaly
-----------------------------------------------
Based on the data, the water level for `reservoir_1` exceeded the safety limit around timestep 350. 
Probable Cause:
1. A sudden, large inflow disturbance occurred at timestep 320.
2. The `gate_control_agent` response was too slow, with its integral (I) term accumulating error, leading to overshoot.

Recommendation:
- Implement a feed-forward term in the gate controller to react faster to inflow changes.
- Add an `EmergencyAgent` to override local control when critical thresholds are breached.
            """
        else:
            return "I have analyzed the data but could not form a specific conclusion for your query. Please try a different question."
