output:
- file: twin_reservoir_log.csv
  topic: state/twin_reservoir
- file: true_reservoir_log.csv
  topic: state/true_reservoir
- file: identified_params_log.json
  topic: identified_parameters/twin_reservoir
simulation:
  end_time: 720000
  real_time_factor: 1.0
  start_time: 0.0
  time_step: 3600
