apiVersion: v1
kind: Namespace
metadata:
  name: chs-simulation
  labels:
    name: chs-simulation
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: chs-simulation-staging
  labels:
    name: chs-simulation-staging
    environment: staging