from .authentication import (
    AuthenticationError,
    TokenManager,
    UserAuthenticator
)
from .authorization import (
    Permission,
    Role,
    AuthorizationError,
    PermissionChecker,
    check_permissions,
    require_permissions,
    require_role,
    require_ownership_or_admin,
    is_admin,
    is_superuser,
    can_create_simulation,
    can_access_admin_panel
)
from .models import (
    UserRole,
    TokenType,
    UserCreate,
    UserUpdate,
    UserPasswordUpdate,
    UserResponse,
    UserLogin,
    TokenData,
    Token,
    TokenRefresh,
    PasswordReset,
    PasswordResetConfirm,
    UserPreferences,
    UserSession,
    LoginAttempt,
    UserActivity,
    PermissionCheck,
    PermissionResponse,
    RoleUpdate,
    BulkUserOperation,
    UserStats,
    SecurityEvent
)
from .dependencies import (
    get_current_user,
    get_current_user_optional,
    get_current_active_user,
    require_admin,
    require_moderator,
    require_user_management,
    require_simulation_management,
    require_simulation_read,
    require_simulation_write,
    require_data_access,
    require_websocket_access,
    api_rate_limiter,
    auth_rate_limiter,
    websocket_rate_limiter
)

__all__ = [
    # Authentication
    "AuthenticationError",
    "TokenManager",
    "UserAuthenticator",
    
    # Authorization
    "Permission",
    "Role",
    "AuthorizationError",
    "PermissionChecker",
    "check_permissions",
    "require_permissions",
    "require_role",
    "require_ownership_or_admin",
    "is_admin",
    "is_superuser",
    "can_create_simulation",
    "can_access_admin_panel",
    
    # Models
    "UserRole",
    "TokenType",
    "UserCreate",
    "UserUpdate",
    "UserPasswordUpdate",
    "UserResponse",
    "UserLogin",
    "TokenData",
    "Token",
    "TokenRefresh",
    "PasswordReset",
    "PasswordResetConfirm",
    "UserPreferences",
    "UserSession",
    "LoginAttempt",
    "UserActivity",
    "PermissionCheck",
    "PermissionResponse",
    "RoleUpdate",
    "BulkUserOperation",
    "UserStats",
    "SecurityEvent",
    
    # Dependencies
    "get_current_user",
    "get_current_user_optional",
    "get_current_active_user",
    "require_admin",
    "require_moderator",
    "require_user_management",
    "require_simulation_management",
    "require_simulation_read",
    "require_simulation_write",
    "require_data_access",
    "require_websocket_access",
    "api_rate_limiter",
    "auth_rate_limiter",
    "websocket_rate_limiter",
]