simulation:
  duration: 200
  dt: 1.0
  name: 通用配置文件
  solver: rk4
components:
- id: flood_gate
  type: Gate
  params: {}
- id: main_reservoir
  type: Reservoir
  params: {}
topology:
- from: main_reservoir
  to: flood_gate
  type: flow
agents:
- id: central_dispatcher
  type: CentralDispatcher
  params: {}
- id: reservoir_twin
  type: DigitalTwin
  params: {}
